import { describe, expect, it } from 'vitest'
import { extractTypeorm } from '../../src/adapters/typeorm/index.js'
import type { Operation } from '../../src/ir/types.js'
import type { Dialect } from '../../src/rules/types.js'
import { parseMigrations } from '../../src/sql/index.js'

/** Runs one up() body through extraction and parsing, and drops position fields. */
async function bodies(body: string, dialect: Dialect = 'postgres'): Promise<unknown[]> {
  const text = `import { Table, TableColumn, TableForeignKey, TableIndex, TableUnique, TableCheck } from 'typeorm'
export class Parity1727300000000 {
  async up(queryRunner) {
    ${body}
  }
}
`
  const extracted = extractTypeorm({ path: 'parity.ts', text }, { dialect, options: {} })
  const [migration] = await parseMigrations(extracted, { dialect })
  return (migration?.up ?? []).map((op: Operation) => {
    const omit = new Set(['loc', 'origin', 'sql', 'conditional', 'batch'])
    return Object.fromEntries(Object.entries(op).filter(([key]) => !omit.has(key)))
  })
}

async function expectSame(builder: string, sql: string, dialect: Dialect = 'postgres') {
  const fromBuilder = await bodies(builder, dialect)
  const fromSql = await bodies(`await queryRunner.query(${JSON.stringify(sql)})`, dialect)
  expect(fromBuilder.length).toBeGreaterThan(0)
  expect(fromSql).toEqual(fromBuilder)
}

describe('builder calls and SQL produce the same operations (PostgreSQL)', () => {
  it.each([
    [
      'create_table',
      `await queryRunner.createTable(new Table({ name: 'audit', columns: [] }))`,
      'CREATE TABLE "audit" ("id" int)',
    ],
    ['drop_table', `await queryRunner.dropTable('audit')`, 'DROP TABLE "audit"'],
    [
      'rename_table',
      `await queryRunner.renameTable('users', 'accounts')`,
      'ALTER TABLE "users" RENAME TO "accounts"',
    ],
    [
      'add_column (varchar, NOT NULL, constant default)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'name', type: 'character varying', length: '255', default: "'x'" }))`,
      `ALTER TABLE "users" ADD "name" character varying(255) NOT NULL DEFAULT 'x'`,
    ],
    [
      'add_column (nullable int)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'age', type: 'int', isNullable: true }))`,
      'ALTER TABLE "users" ADD "age" integer',
    ],
    [
      'add_column (volatile default)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'token', type: 'uuid', default: 'gen_random_uuid()' }))`,
      'ALTER TABLE "users" ADD "token" uuid NOT NULL DEFAULT gen_random_uuid()',
    ],
    [
      'add_column (serial)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'seq', type: 'int', isGenerated: true, generationStrategy: 'increment' }))`,
      'ALTER TABLE "users" ADD "seq" serial',
    ],
    [
      'add_column (identity)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'num', type: 'int', isGenerated: true, generationStrategy: 'identity' }))`,
      'ALTER TABLE "users" ADD "num" integer GENERATED BY DEFAULT AS IDENTITY',
    ],
    [
      'add_column (stored generated)',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'twice', type: 'int', isNullable: true, generatedType: 'STORED', asExpression: 'num * 2' }))`,
      'ALTER TABLE "users" ADD "twice" integer GENERATED ALWAYS AS (num * 2) STORED',
    ],
    [
      'drop_column',
      `await queryRunner.dropColumn('users', 'legacy')`,
      'ALTER TABLE "users" DROP COLUMN "legacy"',
    ],
    [
      'rename_column',
      `await queryRunner.renameColumn('users', 'age', 'years')`,
      'ALTER TABLE "users" RENAME COLUMN "age" TO "years"',
    ],
    [
      'create_index',
      `await queryRunner.createIndex('users', new TableIndex({ name: 'IDX_e', columnNames: ['email'], isUnique: true, isConcurrent: true }))`,
      'CREATE UNIQUE INDEX CONCURRENTLY "IDX_e" ON "users" ("email")',
    ],
    [
      'drop_index',
      `await queryRunner.dropIndex('users', new TableIndex({ name: 'IDX_e', columnNames: [], isConcurrent: true }))`,
      'DROP INDEX CONCURRENTLY "IDX_e"',
    ],
    [
      'add_constraint (foreign key)',
      `await queryRunner.createForeignKey('posts', new TableForeignKey({ name: 'FK_a', columnNames: ['a'], referencedTableName: 'users', referencedColumnNames: ['id'] }))`,
      'ALTER TABLE "posts" ADD CONSTRAINT "FK_a" FOREIGN KEY ("a") REFERENCES "users"("id")',
    ],
    [
      'add_constraint (unique)',
      `await queryRunner.createUniqueConstraint('users', new TableUnique({ name: 'UQ_e', columnNames: ['email'] }))`,
      'ALTER TABLE "users" ADD CONSTRAINT "UQ_e" UNIQUE ("email")',
    ],
    [
      'add_constraint (check)',
      `await queryRunner.createCheckConstraint('users', new TableCheck({ name: 'CHK_a', expression: 'a > 0' }))`,
      'ALTER TABLE "users" ADD CONSTRAINT "CHK_a" CHECK (a > 0)',
    ],
    [
      'add_constraint (primary key)',
      `await queryRunner.createPrimaryKey('users', ['id'], 'PK_u')`,
      'ALTER TABLE "users" ADD CONSTRAINT "PK_u" PRIMARY KEY ("id")',
    ],
    ['truncate', `await queryRunner.clearTable('sessions')`, 'TRUNCATE "sessions"'],
    ['transaction_control', `await queryRunner.commitTransaction()`, 'COMMIT'],
    [
      'set_not_null (from changeColumn)',
      `await queryRunner.changeColumn('users', new TableColumn({ name: 'a', type: 'int', isNullable: true }), new TableColumn({ name: 'a', type: 'int' }))
       await queryRunner.query('SELECT 1')`,
      '',
    ],
  ])('%s', async (_, builder, sql) => {
    if (sql === '') {
      // changeColumn also reports TypeORM's own operation, so compare only the core part.
      const ops = await bodies(builder)
      const fromSql = await bodies(
        `await queryRunner.query('ALTER TABLE "users" ALTER COLUMN "a" SET NOT NULL')`,
      )
      expect(ops).toContainEqual(fromSql[0])
      return
    }
    await expectSame(builder, sql)
  })

  it('drop_constraint: SQL cannot name the constraint type, the builder can', async () => {
    const [fromBuilder] = await bodies(`await queryRunner.dropForeignKey('posts', 'FK_a')`)
    const [fromSql] = await bodies(
      `await queryRunner.query('ALTER TABLE "posts" DROP CONSTRAINT "FK_a"')`,
    )
    expect(fromSql).toEqual({
      kind: 'drop_constraint',
      table: { schema: 'public', name: 'posts' },
      name: 'FK_a',
    })
    expect(fromBuilder).toEqual({ ...(fromSql as object), type: 'foreign_key' })
  })
})

describe('builder calls and SQL produce the same operations (MySQL)', () => {
  it.each([
    [
      'add_column',
      `await queryRunner.addColumn('users', new TableColumn({ name: 'name', type: 'varchar', length: '255' }))`,
      'ALTER TABLE `users` ADD `name` varchar(255) NOT NULL',
    ],
    [
      'drop_column',
      `await queryRunner.dropColumn('users', 'legacy')`,
      'ALTER TABLE `users` DROP COLUMN `legacy`',
    ],
    [
      'create_index',
      `await queryRunner.createIndex('users', new TableIndex({ name: 'IDX_e', columnNames: ['email'] }))`,
      'CREATE INDEX `IDX_e` ON `users` (`email`)',
    ],
    ['drop_table', `await queryRunner.dropTable('audit')`, 'DROP TABLE `audit`'],
  ])('%s', async (_, builder, sql) => {
    await expectSame(builder, sql, 'mysql')
  })
})
